

[Audio]
UseAudioMixer=True

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
!D3D12TargetedShaderFormats=ClearArray
+D3D12TargetedShaderFormats=PCD3D_SM6

[/Script/Engine.RendererSettings]
r.AllowStaticLighting=0
r.GenerateMeshDistanceFields=True
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Shadow.Virtual.Enable=1
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
r.DefaultFeature.LocalExposure.HighlightContrastScale=0.8
r.DefaultFeature.LocalExposure.ShadowContrastScale=0.8
r.SkinCache.CompileShaders=True
r.RayTracing=True
r.RayTracing.RayTracingProxies.ProjectEnabled=True
r.Substrate=True
r.Substrate.ProjectGBufferFormat=0

[/Script/WorldPartitionEditor.WorldPartitionEditorSettings]
CommandletClass=Class'/Script/UnrealEd.WorldPartitionConvertCommandlet'

[/Script/Engine.UserInterfaceSettings]
bAuthorizeAutomaticWidgetVariableCreation=False
FontDPIPreset=Standard
FontDPI=72

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=CE8DAB69493704BC79E160B32B5B4872
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

; 언리얼 엔진이  Online SubSystem Steam을 사용하도록 설정
[OnlineSubsystem]
DefaultPlatformService=Steam

; OnlineSubsystemSteam 모듈 환경설정
[OnlineSubsystemSteam]
bEnabled=true
; 테스트용 App ID
SteamDevAppId=480	
bAllowP2PPacketRelay=true
; 세션 사용
bInitServerOnClient=true

; 애플리케이션 연결을 위한 넷 드라이버 Steam 클래스를 지정
[/Script/OnlineSubsystemSteam.SteamNetDriver]
NetConnectionClassName="OnlineSubsystemSteam.SteamNetConnection"

; NetDriverDefinitions: 아래 프로퍼티로 들어오는 넥 드라이버를 설명
; 1. DefName: 넷 드라이버 정의 고유 이름
; 2. DriverClassName: 주요 넷 드라이버의 클래스 이름
; 3. DriverClassNameFallBack: 주요 넷 드라이버 클래스의 초기화에 실패한 경우 예비 넷 드라이버
[/Script/Engine.GameEngine]
+NetDriverDefinitions=(DefName="GameNetDriver", DriverClassName="/Script/OnlineSubsystemSteam.SteamNetDriver", DriverClassNameFallback="OnlineSubsystemUtils.IpNetDriver")

[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/Levels/TestLevel.TestLevel
GameDefaultMap=/Game/Levels/TestLevel.TestLevel

