[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=8254B2EB4484C4F563FB1CAEB22D663B

[/Script/UnrealEd.ProjectPackagingSettings]
; TableSubsystem loads these assets from string paths at runtime. Because string paths
; are not cook dependencies, explicitly include the data-table directory in packages.
+DirectoriesToAlwaysCook=(Path="/Game/Table")

[/Script/CommonUI.CommonUISettings]
CommonButtonAcceptKeyHandling=TriggerClick
